name = "nearfolk-leaderboard"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "NEARFOLK_KV"
id = "e92b049c9d414cea85e10edde3c84a2b"

[vars]
HMAC_SECRET = "nearfolk-prod-2026-vibejam"
